final foodMapList = [
    {
    "name":"Mì Quảng",
    "type":1, /*1 food / 2 drink , 3 vege , 4 cake , 5 deseert */
    "rating":3.5,
    "goodReviews":12,
    "price":"45,000 - 60,000",
    "isfavourite":false,
    "image":"images/food/miquang.jpg",
    "address":"Trần Hưng Đạo, P. 7, Quận 5, TP. HCM",
    "description":"Món ăn này là đặc sản của tỉnh Quảng Nam nhưng được ưa chuộng trên khắp cả nước. Nguyên liệu gồm sợi mì, đậu phộng, bánh đa, thịt lợn quay và nước dùng có màu vàng của nghệ. Không ít du khách quốc tế khi được thưởng thức mì Quảng khi đến Việt Nam đã ca ngợi đây là món ăn hoàn hảo.",
  },
  {
    "name":"Phở",
    "type":1, /*1 food / 2 drink , 3 vege , 4 cake , 5 deseert */
    "rating":4.5,
    "goodReviews":38,
    "price":"25,000 - 65,000",
    "isfavourite":true,
    "image":"images/food/pho.jpg",
    "address":"Trần Hưng Đạo, P. 7, Quận 5, TP. HCM",
    "description":"Mỗi ngày ở Việt Nam có hàng triệu bát phở được phục vụ. Đây luôn được coi là món ăn nổi tiếng nhất và hấp dẫn nhất của nền ẩm thực Việt trong mắt du khách quốc tế.",
  },
  {
    "name":"Gỏi cuốn",
    "type":1, /*1 food / 2 drink , 3 vege , 4 cake , 5 deseert */
    "rating":4.0,
    "goodReviews":123,
    "price":"25,000 - 35,000",
    "isfavourite":false,
    "image":"images/food/goicuon.jpg",
    "address":"Trần Hưng Đạo, P. 7, Quận 5, TP. HCM",
    "description":"Đây là món ăn nhẹ hoàn hảo của Việt Nam, với các thành phần chính như tôm, miến, thịt lợn và rau xanh rất tốt cho sức khỏe được bọc trong lớp bánh tráng mỏng, dai.",
  },
  {
    "name":"Bò kho",
    "type":1, /*1 food / 2 drink , 3 vege , 4 cake , 5 deseert */
    "rating":4.5,
    "goodReviews":12,
    "price":"25,000 - 35,000",
    "isfavourite":false,
    "image":"images/food/bokho.jpg",
    "address":"Trần Hưng Đạo, P. 7, Quận 5, TP. HCM",
    "description":"Món ăn này được đặc biệt yêu thích vào bữa sáng hoặc trưa. Đầu bếp có thể thay thế thịt bò bằng bất kỳ loại thịt nào khác, ninh trong lửa nhỏ với nước mắm, đường và nước dừa tươi, cà rốt, hành tây và rau mùi. Cách ăn phổ biến nhất để thưởng thức món này là xé từng miếng bánh mì rồi nhúng vào phần nước sốt và ăn kèm với thịt hầm.",
  },
  //
  {
    "name":"Bún chả",
    "type":1, /*1 food / 2 drink , 3 vege , 4 cake , 5 deseert */
    "rating":2.5,
    "goodReviews":12,
    "price":"15,000 - 35,000",
    "isfavourite":false,
    "image":"images/food/buncha.jpg",
    "address":"Trần Hưng Đạo, P. 7, Quận 5, TP. HCM",
    "description":"Bún chả là một đại diện của phong cách ẩm thực Hà Nội. Các thành phần chính gồm bún gạo, thịt lợn nướng, nước mắm và rất nhiều loại gia vị và rau thơm ăn kèm.",
  },
  {
    "name":"Chả giò (miền Nam) / Nem rán (miền Bắc)",
    "type":1, /*1 food / 2 drink , 3 vege , 4 cake , 5 deseert */
    "rating":5,
    "goodReviews":12,
    "price":"15,000 - 35,000",
    "isfavourite":false,
    "image":"images/food/chagio.jpg",
    "address":"",
    "description":"Những chiếc nem được làm từ thịt lợn băm, trứng, nấm tai mèo và các loại rau củ được gói trong bánh tráng rồi chiên giòn ngập dầu. Món ăn này phổ biến trên toàn thế giới với nhiều phiên bản khác nhau.",
  },
  {
    "name":"Bún mắm",
    "type":1, /*1 food / 2 drink , 3 vege , 4 cake , 5 deseert */
    "rating":1.5,
    "goodReviews":33,
    "price":"20,000 - 30,000",
    "isfavourite":false,
    "image":"images/food/bunmam.jpg",
    "address":"Trần Hưng Đạo, P. 7, Quận 5, TP. HCM",
    "description":"Món ăn này được người dân địa phương biến tấu với nhiều nguyên liệu khác nhau, tùy theo từng vùng miền, nhưng những thành phần dưới đây là không thể thiếu: bún gạo, hải sản, thịt lợn, một số loại rau gia vị và đặc biệt là mắm nêm.",
  },
  {
    "name":"Gà nướng sả",
    "type":1, /*1 food / 2 drink , 3 vege , 4 cake , 5 deseert */
    "rating":1.5,
    "goodReviews":12,
    "price":"95,000 - 285,000",
    "isfavourite":false,
    "image":"images/food/ganuongsa.jpg",
    "address":"Trần Hưng Đạo, P. 7, Quận 5, TP. HCM",
    "description":"Gà nướng sả cũng tương tự như các món bún nổi tiếng khác của Việt Nam, chỉ khác là nguyên liệu chính từ thịt gà ướp sả, nướng thơm phức vô cùng hấp dẫn.",
  },
  {
    "name":"Cơm tấm",
    "type":1, /*1 food / 2 drink , 3 vege , 4 cake , 5 deseert */
    "rating":3.5,
    "goodReviews":12,
    "price":"15,000 - 45,000",
    "isfavourite":false,
    "image":"images/food/comtam.jpg",
    "address":"Trần Hưng Đạo, P. 7, Quận 5, TP. HCM",
    "description":"Đây là bữa trưa vô cùng phổ biến ở Sài Gòn, với đĩa cơm tấm ăn kèm với thịt lợn hoặc sườn lợn nướng, dưa muối chua và một số loại rau gia vị.",
  },
  //
  {
    "name":"Mực chiên",
    "type":1, /*1 food / 2 drink , 3 vege , 4 cake , 5 deseert */
    "rating":5,
    "goodReviews":112,
    "price":"25,000 - 75,000",
    "isfavourite":true,
    "image":"images/food/comtam.jpg",
    "address":"932 Trần Hưng Đạo, P. 7, Quận 5, TP. HCM",
    "description":"Việt Nam là một quốc gia ven biển, vì vậy mực tươi rất dễ mua và phổ biến trong ẩm thực Việt. Thông thường, mực ống được sắt miếng vừa phải và tẩm bột chiên giòn. Món ăn này được mọi lứa tuổi và vùng miền yêu thích vì rất dễ ăn.",
  },
  {
    "name":"Bún bò Huế",
    "type":1, /*1 food / 2 drink , 3 vege , 4 cake , 5 deseert */
    "rating":5,
    "goodReviews":123,
    "price":"25,000 - 45,000",
    "isfavourite":false,
    "image":"images/food/bunbohue.jpg",
    "address":"Trần Hưng Đạo, P. 7, Quận 5, TP. HCM",
    "description":"Ẩm thực cố đô Huế nổi tiếng với hương vị hài hòa giữa cay, chua, mặn và ngọt - và Bún bò Huế là một ví dụ tuyệt vời. Nước dùng được làm từ nước xương bò ninh với sả và nước mắm. Bát bún được phục vụ với thịt bò, thịt lợn, sợi bún to và dày hơn của miền Bắc và rất nhiều loại rau gia vị. Đặc biệt, người Huế rất thích ăn cay, vì vậy, ớt và tiêu là 2 thứ không thể thiếu để làm nên hương vị đặc biệt của món ăn này.",
  },
  {
    "name":"Bánh mì",
    "type":1, /*1 food / 2 drink , 3 vege , 4 cake , 5 deseert */
    "rating":4.5,
    "goodReviews":121,
    "price":"10,000 - 25,000",
    "isfavourite":true,
    "image":"images/food/banhmi.jpg",
    "address":"Trần Hưng Đạo, P. 7, Quận 5, TP. HCM",
    "description":"Hàng triệu ổ bánh mì được nướng mỗi ngày, không chỉ ngon, giá rẻ mà còn đầy đủ chất dinh dưỡng và cơ động cho một bữa sáng vội vàng.",
  },
  {
    "name":"Cá kho tộ",
    "type":1, /*1 food / 2 drink , 3 vege , 4 cake , 5 deseert */
    "rating":4.5,
    "goodReviews":32,
    "price":"25,000 - 35,000",
    "isfavourite":false,
    "image":"images/food/cakhoto.jpg",
    "address":"Trần Hưng Đạo, P. 7, Quận 5, TP. HCM",
    "description":"Cá được đun sôi liên tục trong dầu ăn, nước hàng, tỏi, hành, muối, nước mắm và nước dừa bên trong nồi đất sét nung tạo nên hương vị vô cùng hấp dẫn.",
  },
  {
    "name":"Bánh xèo",
    "type":1, /*1 food / 2 drink , 3 vege , 4 cake , 5 deseert */
    "rating":4.5,
    "goodReviews":12,
    "price":"15,000 - 35,000",
    "isfavourite":true,
    "image":"images/food/banhxeo.jpg",
    "address":"Trần Hưng Đạo, P. 7, Quận 5, TP. HCM",
    "description":"Bột bánh xèo được làm từ bột gạo và bột nghệ, tráng mỏng, giòn, phần nhân làm từ thịt bò, tôm, giá đỗ ăn kèm với các loại rau thơm, chấm nước mắm chua ngọt vô cùng hấp dẫn.",
  },
  {
    "name":"Rau muống xào tỏi",
    "type":1, /*1 food / 2 drink , 3 vege , 4 cake , 5 deseert */
    "rating":1.5,
    "goodReviews":12,
    "price":"10,000 - 30,000",
    "isfavourite":true,
    "image":"images/food/raumuong.jpg",
    "address":"Trần Hưng Đạo, P. 7, Quận 5, TP. HCM",
    "description":"Rau muống xanh mướt được xào với tỏi và dầu ăn béo ngậy. Ngay cả những người không thích ăn rau xanh cũng dễ “xiêu lòng” với món ăn dân dã này.",
  },
  {
    "name":"Cao lầu",
    "type":1, /*1 food / 2 drink , 3 vege , 4 cake , 5 deseert */
    "rating":2.5,
    "goodReviews":32,
    "price":"15,000 - 20,000",
    "isfavourite":false,
    "image":"images/food/caolau.jpg",
    "address":"Trần Hưng Đạo, P. 7, Quận 5, TP. HCM",
    "description":"Món cao lầu là đặc sản của Hội An. Dù được biến tấu theo nhiều phong cách và hương vị khác nhau, nhưng món ăn này chỉ hấp dẫn nhất khi được thưởng thức tại quê hương của nó.",
  },
  {
    "name":"Chả cá",
    "type":1, /*1 food / 2 drink , 3 vege , 4 cake , 5 deseert */
    "rating":1.5,
    "goodReviews":54,
    "price":"60,000 - 110,000",
    "isfavourite":true,
    "image":"images/food/chaca.jpg",
    "address":"Trần Hưng Đạo, P. 7, Quận 5, TP. HCM",
    "description":"Cá được ướp với bột nghệ, gừng, tỏi và nước mắm. Khi ăn, thực khách sẽ chiên nó trên chảo với rau thì là và hành lá, ăn kèm với bún gạo. Giống như các món ăn khác của ẩm thực Hà Nội, chả cá là sự cân bằng hoàn hảo của hương vị và kết cấu.",
  },
    {
    "name":"Bột chiên",
    "type":1, /*1 food / 2 drink , 3 vege , 4 cake , 5 deseert */
    "rating":1.5,
    "goodReviews":132,
    "price":"15,000 - 25,000",
    "isfavourite":false,
    "image":"images/food/botchien.jpg",
    "address":"Trần Hưng Đạo, P. 7, Quận 5, TP. HCM",
    "description":"Bột chiên giòn với trứng và hành lá là món ăn sáng khá hấp dẫn. Món ăn này thường được bày bán trên các xe đẩy ở đường phố miền Nam Việt Nam.",
  },
  //
  {
    "name":"Trà sen",
    "type":2, /*1 food / 2 drink , 3 vege , 4 cake , 5 deseert */
    "rating":5,
    "goodReviews":123,
    "price":"15,000 - 25,000",
    "isfavourite":false,
    "image":"images/drink/trasen.jpg",
    "address":"Trần Hưng Đạo, P. 7, Quận 5, TP. HCM",
    "description":"Trà sen (hay chè sen) là một loại trà được ướp hương sen. Với sự tinh tế trong cách chuẩn bị, pha chế và những nguyên liệu mang phong vị của đất nước ta, trà sen đã trở thành đại diện của văn hóa trà Việt Nam, góp phần vào nền văn hóa trà trên thế giới.",
  },
  {
    "name":"Cà phê",
    "type":2, /*1 food / 2 drink , 3 vege , 4 cake , 5 deseert */
    "rating":4.5,
    "goodReviews":12,
    "price":"10,000 - 15,000",
    "isfavourite":false,
    "image":"images/drink/caphe.jpg",
    "address":"Trần Hưng Đạo, P. 7, Quận 5, TP. HCM",
    "description":"Việt Nam đứng thứ 2 trên thế giới về sản xuất cà phê. Cà phê ở Việt Nam có nhiều thương hiệu nổi tiếng. Ngày nay, tại Hà Nội, Thành phố Hồ Chí Minh, Đà Nẵng, Nha Trang hay nhiều thành phố khác có vô số quán cà phê. Trong số thương hiệu cà phê tại Việt Nam có Ground là phổ biến hơn và người Việt Nam rất thích dùng cà phê pha phin.",
  },
  {
    "name":"Nước dừa",
    "type":2, /*1 food / 2 drink , 3 vege , 4 cake , 5 deseert */
    "rating":5,
    "goodReviews":132,
    "price":"10,000 - 20,000",
    "isfavourite":true,
    "image":"images/drink/nuocdua.jpg",
    "address":"Trần Hưng Đạo, P. 7, Quận 5, TP. HCM",
    "description":"Nước dừa đã trở thành một loại nước giải khát phổ biến ở Việt Nam trong nhiều thế kỷ. Tại Việt Nam, không cần uống nước dừa trong hộp kín, có thể dùng trực tiếp từ dừa tươi để thưởng thức hương vị dừa nguyên chất và ngọt.",
  },
  {
    "name":"Nước mía",
    "type":2, /*1 food / 2 drink , 3 vege , 4 cake , 5 deseert */
    "rating":5,
    "goodReviews":123,
    "price":"5,000 - 10,000",
    "isfavourite":false,
    "image":"images/drink/nuocmia.jpg",
    "address":"Trần Hưng Đạo, P. 7, Quận 5, TP. HCM",
    "description":"Nước mía là một trong những loại đồ uống giúp giải nhiệt trong mùa hè. Dưới cái nắng oi bức của mùa hè, không hề khó tìm kiếm một quán hàng bán nước mía. Chỉ cần một cái máy ép cùng cây mía là có thể chế ra một cốc nước mía.",
  },
  {
    "name":"Bia hơi",
    "type":2, /*1 food / 2 drink , 3 vege , 4 cake , 5 deseert */
    "rating":3.5,
    "goodReviews":72,
    "price":"10,000 - 15,000",
    "isfavourite":false,
    "image":"images/drink/bia.jpg",
    "address":"Trần Hưng Đạo, P. 7, Quận 5, TP. HCM",
    "description":"Bia hơi phổ biến nhất, ngon và tươi nhất ở Việt Nam. Một quán bia hơi góc phố luôn thu hút bởi sự ồn ào, náo nhiệt gây ra chủ yếu bởi những người đàn ông Việt Nam. Bia hơi có độ cồn thấp (dưới 3%), giá rẻ (1 USD/ 1 lít) nên rất được khách Tây ưa chuộng.",
  },
  //
  {
    "name":"Cocktail",
    "type":1, /*1 food / 2 drink , 3 vege , 4 cake , 5 deseert */
    "rating":2.5,
    "goodReviews":28,
    "price":"15,000 - 25,000",
    "isfavourite":true,
    "image":"images/drink/cocktail.jpg",
    "address":"Trần Hưng Đạo, P. 7, Quận 5, TP. HCM",
    "description":"Hiện nay, các loại cocktail khá phổ biến trong các nhà hàng, quán bar. Một số các quán café đã bổ sung cocktail vào thực đơn đa dạng của mình . Cocktail quả thật là một thức uống tiềm năng cần được khai phá để tăng lợi nhuận cho doanh nghiệp.",
  },
  {
    "name":"Chocolate nóng",
    "type":1, /*1 food / 2 drink , 3 vege , 4 cake , 5 deseert */
    "rating":3.5,
    "goodReviews":30,
    "price":"25,000 - 35,000",
    "isfavourite":true,
    "image":"images/drink/chocolatenong.jpg",
    "address":"Trần Hưng Đạo, P. 7, Quận 5, TP. HCM",
    "description":"Các loại đồ uống nóng như chocolate nóng, ca cao nóng hiện nay cũng được rất nhiều người ưa chuộng. Đồ uống nóng thường được sử dụng vào mùa đông để giữ ấm cơ thể. Hoặc có nhiều khách hàng chỉ thích các thức uống nóng.",
  },
  {
    "name":"Mojito Soda",
    "type":1, /*1 food / 2 drink , 3 vege , 4 cake , 5 deseert */
    "rating":3.5,
    "goodReviews":12,
    "price":"15,000 - 20,000",
    "isfavourite":true,
    "image":"images/drink/mojito.jpg",
    "address":"Trần Hưng Đạo, P. 7, Quận 5, TP. HCM",
    "description":"Mojito có xuất xứ từ Cuba bao gồm rượu Rum trắng, đường mía, chanh và bạc hà. Ngoài các thành phần cơ bản như trên, Mojito còn có nhiều cách pha chế khác nhau như hoa quả tươi, sữa hoặc các mùi vị khác nhau tùy theo ý thích của người dùng.",
  },
  {
    "name":"Bánh Gato",
    "type":3, /*1 food / 2 drink , 3 vege , 4 cake , 5 deseert */
    "rating":4.5,
    "goodReviews":105,
    "price":"95,000 - 200,000",
    "isfavourite":true,
    "image":"images/cake/gato.jpg",
    "address":"Trần Hưng Đạo, P. 7, Quận 5, TP. HCM",
    "description":"Mẫu mã các loại bánh càng ngày càng đẹp, hương vị bánh và kem cũng dần thay đổi để phù hợp với xu thế. Một chiếc bánh gato ngon cần phải có phần cốt bánh bông xốp, nhẹ, ăn không bị bứ. Bên cạnh đó thì lượng kem cũng cần vừa phải, không quá nhiều hay quá ít, không quá ngọt cũng không quá nhạt, và quan trọng nhất là không bị ngán.",
  },
  {
    "name":"Bánh Tiramisu",
    "type":3, /*1 food / 2 drink , 3 vege , 4 cake , 5 deseert */
    "rating":1.5,
    "goodReviews":18,
    "price":"50,000 - 90,000",
    "isfavourite":false,
    "image":"images/cake/tiramisu.jpg",
    "address":"Trần Hưng Đạo, P. 7, Quận 5, TP. HCM",
    "description":"Đây là một loại bánh đến từ nước Ý. Trong những năm gần đây, bánh tiramisu được trở thành một trong 5 loại bánh kem sinh nhật ưa thích và được làm thành kích cỡ to, trang trí như một chiếc bánh sinh nhật có thể làm tâm điểm cho bữa tiệc sinh nhật. Phần cốt bánh mềm xốp, thấm đẫm hương vị cà phê và rượu rum, phần kem được phết giữa các lớp béo ngậy nhưng lại cực kỳ dễ ăn.",
  },
  {
    "name":"Bánh Cheesecake",
    "type":3, /*1 food / 2 drink , 3 vege , 4 cake , 5 deseert */
    "rating":2.5,
    "goodReviews":8,
    "price":"35,000 - 100,000",
    "isfavourite":false,
    "image":"images/cake/cheesecake.jpg",
    "address":"Trần Hưng Đạo, P. 7, Quận 5, TP. HCM",
    "description":"Cùng giống như dòng bánh mousse, nhưng thành phần để làm nên cheesecake ngoài kem whipping còn có phần cream cheese chua chua béo ngậy. Cream cheese là thành phần chính và làm nên độ ngon không thể chối từ của cheesecake, khiến nó trở thành một trong 5 loại bánh kem sinh nhật được chị em tìm kiếm công thức nhiều nhất.",
  },
    {
    "name":"Sầu riêng",
    "type":4, /*1 food / 2 drink , 3 vege , 4 cake , 5 deseert */
    "rating":5,
    "goodReviews":657,
    "price":"15,000 - 120,000",
    "isfavourite":true,
    "image":"images/vege/saurieng.jpg",
    "address":"Trần Hưng Đạo, P. 7, Quận 5, TP. HCM",
    "description":"Sầu riêng còn được nhiều người yêu thích loại quả này gọi bằng danh xưng “vua của các loại trái cây” do sở hữu mùi thơm mạnh cùng độ ngọt, béo không lẫn vào đâu được. Mặc dù có nhiều ý kiến trái ngược nhau về mùi của thức quả này nhưng nó được ghi nhận chứa hàm lượng protein, glucid, lipid, các chất khoáng và giá trị năng lượng cao hơn hẳn so với các loại trái cây khác. Khoảng tháng 7 - 8 trở đi là thời điểm thích hợp để thưởng thức những quả sầu riêng thơm nức mũi vì lúc ấy đã chính vụ. Do không chịu được khí hậu lạnh nên loại quả này chỉ trồng được ở các tỉnh phía nam từ Thừa Thiên Huế - Quảng Trị trở vào.",
  },
  {
    "name":"Măng cụt ",
    "type":4, /*1 food / 2 drink , 3 vege , 4 cake , 5 deseert */
    "rating":4.5,
    "goodReviews":35,
    "price":"10,000 - 300,000",
    "isfavourite":false,
    "image":"images/vege/mangcut.jpg",
    "address":"Trần Hưng Đạo, P. 7, Quận 5, TP. HCM",
    "description":"Măng cụt khi chín có vỏ dày, màu đỏ tím đậm. Đã “ghiền” loại quả này thì dù bao lần tách vỏ cũng phải dán mắt vào từng múi măng cụt trắng ngà, thơm thoang thoảng, vị thì chua ngọt thanh thanh tan trong miệng. Mùa măng cụt cũng khá chóng vánh, chỉ rộ vào giữa tháng 4 đến tháng 6, qua mùa bạn sẽ khó mua được măng cụt ngon.",
  },
  {
    "name":"Bòn bon (Nam trân)",
    "type":4, /*1 food / 2 drink , 3 vege , 4 cake , 5 deseert */
    "rating":3.5,
    "goodReviews":52,
    "price":"15,000 - 70,000",
    "isfavourite":false,
    "image":"images/vege/bonbon.jpg",
    "address":"Trần Hưng Đạo, P. 7, Quận 5, TP. HCM",
    "description":"Mỗi mùa bòn bon chín, khi cùng ngồi thưởng thức vị ngọt thanh xen lẫn chút chua của loại quả này, chúng ta lại nhớ câu chuyện xa xưa về nguồn gốc “mùa quả tiến vua”. Tương truyền, lúc đoàn quân chúa Nguyễn chạy trốn binh lính Tây Sơn trong rừng bị cạn kiệt lương thực, nhờ hái được loại quả ngọt như bòn bon mà vượt qua cơn đói để tiếp tục chinh chiến. Ở nhiều địa phương gọi bòn bon với cái tên khác: loòng boong, lòn bon, phụng quân… và thời điểm để thưởng thức quả này là vào mùa hè từ tháng 5 đến tháng 10. Hiện nay, huyện Tiên Phước (thuộc tỉnh Quảng Nam) nổi tiếng trồng nhiều cây bòn bon cũng như cho sản lượng cao tại nước ta.",
  },
  {
    "name":"Chôm chôm",
    "type":4, /*1 food / 2 drink , 3 vege , 4 cake , 5 deseert */
    "rating":3.5,
    "goodReviews":85,
    "price":"15,000 - 80,000",
    "isfavourite":false,
    "image":"images/vege/chomchom.jpg",
    "address":"Trần Hưng Đạo, P. 7, Quận 5, TP. HCM",
    "description":"Bên cạnh là một loại quả tráng miệng, ăn vặt, ít ai biết rằng chôm chôm (hay lôm chôm) còn mang lại nhiều lợi ích cho cơ thể như: thanh nhiệt (nếu ăn vừa đủ), kháng viêm, loại bỏ độc tố trong thận, tăng sức đề kháng, ngăn ngừa ung thư,… Do đặc tính thích ứng với những vùng không ngập nước mà cây chôm chôm được trồng chủ yếu ở các tỉnh thuộc lưu vực sông Đồng Nai, nam Trung Bộ và đồng bằng sông Cửu Long.",
  },
  {
    "name":"Mận Hà Nội (Mận hậu) – đặc sản miền Bắc.",
    "type":4, /*1 food / 2 drink , 3 vege , 4 cake , 5 deseert */
    "rating":3.5,
    "goodReviews":90,
    "price":"15,000 - 20,000",
    "isfavourite":false,
    "image":"images/vege/man.jpg",
    "address":"Trần Hưng Đạo, P. 7, Quận 5, TP. HCM",
    "description":"Mận hậu có nguồn gốc từ những vùng cao Lào Cai, Lạng Sơn, Mộc Châu,… với khí hậu lạnh dễ dàng cho loài cây này thích nghi và ra trái đạt chuẩn. Đây cũng được xem là một trong những loại quả mang lại giá trị kinh tế cao, giúp ổn định cuộc sống người dân rẻo cao.",
  },
  {
    "name":"Vải (Lệ Chi)",
    "type":4, /*1 food / 2 drink , 3 vege , 4 cake , 5 deseert */
    "rating":2.5,
    "goodReviews":250,
    "price":"15,000 - 20,000",
    "isfavourite":false,
    "image":"images/vege/vai.jpg",
    "address":"Trần Hưng Đạo, P. 7, Quận 5, TP. HCM",
    "description":"Vải trong tiếng Hán Việt còn được gọi là lệ chi, có nguồn gốc từ miền Nam Trung Quốc. Theo sách sử ghi chép, vào thời nhà Đường (Trung Hoa) có Dương Quý Phi – một trong tứ đại mỹ nhân của Trung Quốc rất ưa thích loại trái cây này. Vua Đường Huyền Tông còn sai những phu trạm phi ngựa hỏa tốc để chuyển vải về cho Dương ái Phi.",
  },
  {
    "name":"Xoài",
    "type":4, /*1 food / 2 drink , 3 vege , 4 cake , 5 deseert */
    "rating":1.5,
    "goodReviews":100,
    "price":"15,000 - 20,000",
    "isfavourite":false,
    "image":"images/vege/xoai.jpg",
    "address":"Trần Hưng Đạo, P. 7, Quận 5, TP. HCM",
    "description":"Mặc dù được trồng khắp mọi miền nhưng vùng đất Nam Bộ màu mỡ, trù phú lại phù hợp nhất với giống cây này và cho ra nhiều loại xoài thơm ngon phục vụ nhu cầu trong nước cả xuất khẩu.Thật khó lòng để kể hết tên các loại xoài của vùng miệt thứ, chỉ có thể điểm mặt như: xoài tượng, xoài giòn, xoài tứ quý, xoài keo, xoài Thanh Ca, xoài cát chu, xoài cát Hòa Lộc,…. Và đặc biệt phải nhắc đến xoài ngự - đặc sản huyện Lấp Vò, Đồng Tháp, loại xoài ngon tương truyền được dâng lên vua Gia Long.",
  },
  {
    "name":"Đào Sapa",
    "type":4, /*1 food / 2 drink , 3 vege , 4 cake , 5 deseert */
    "rating":3.5,
    "goodReviews":300,
    "price":"15,000 - 20,000",
    "isfavourite":false,
    "image":"images/vege/dao.jpg",
    "address":"Trần Hưng Đạo, P. 7, Quận 5, TP. HCM",
    "description":"Vào tháng 6 - 7 hằng năm, Sapa lại vào mùa thu hoạch đào chín, đó cũng là lúc nhiều tuyến đường ở Sài Gòn bày bán thức quả thơm thảo này. Những quả đào chỉ nhỏ bằng chén uống trà, màu xanh và hồng đỏ đậm, đi cùng độ giòn, mọng nước, vị chua chua đã làm nên thương hiệu đào Sapa mà ít nơi nào bằng.",
  },
];